OnlineTestingSystem/OnlineTestingSystem.WebUI/Controllers/CertificateController.cs
using OnlineTestingSystem.BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineTestingSystem.WebUI.Controllers
{
    public class CertificateController : Controller
    {
        ICertificateService _certificateService;
        public CertificateController(ICertificateService certificateService)
        {
            _certificateService = certificateService;
        }

        // GET: Certificate
        public ActionResult Index()
        {
            return View();
        }

        //GET: Certificate/Search/?certificateNumber=CN2

        [HttpGet]
        public ActionResult Search(string certificateNumber)
        {
            var s = _certificateService.GetAllCertificates();
            try
            {
                var certificate = _certificateService.GetCertificateByNumber(certificateNumber.ToString());
                return View(certificate);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { @errorText = ex.Message });
            }
        }
    }
}

OnlineTestingSystem/OnlineTestingSystem.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TestService", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Catalog", "AllTests", "Test")</li>
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    }
                    @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                    {
                            <li>@Html.ActionLink("Tests", "Index", "Tests")</li>
                            <li>@Html.ActionLink("Questions", "Index", "Question")</li>
                    }
                </ul>

                @if (!User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav pull-right">
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                        <li>@Html.ActionLink("Registration", "Registration", "Account")</li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-header pull-right" style="margin-top:15px;">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                @User.Identity.Name <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Certificates", "MyCertificates", "Account")
                                </li>
                                <li>
                                    @Html.ActionLink("Sessions", "MyTestsSessions", "Account")
                                </li>
                                <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                            </ul>
                        </li>
                    </ul>

                }

                <div class="form-group">
                    @using (Html.BeginForm("Search", "Certificate", new { id = "certificateNumber" }, FormMethod.Get, new { @class = "navbar-form navbar-left pull-right", @id = "searchCertificateForm" }))
                    {
                        <input type="search" id="certificateNumber" name="certificateNumber" class="form-control" placeholder="Find certificate by ID">
                    }
                </div>

            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <span class="col-md-4" style="text-align:center"> <i class="fa fa-envelope" aria-hidden="true" style="color:darkred"></i> ivashyn.vadym@gmail.com</span>
                <span class="col-md-4" style="text-align:center"> <i class="fa fa-skype" aria-hidden="true" style="color:deepskyblue"></i> zevas.</span>
                <span class="col-md-4" style="text-align:center"> <i class="fa fa-mobile" aria-hidden="true"></i> +38096 85 90 222</span>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $('#certificateNumber').keypress(function (e) {
            if (e.which == 13) {
                $("#searchCertificateForm").submit();
            }
        });
    </script>
</body>
</html>